version: "3"
services: 
  servicemeapi:
    image: cloud.canister.io:5000/okochamoses/serviceme
    # env_file: .env
    environment: 
      - DB_HOST=db:27019&authSource=admin
      - DB_USER=
    depends_on: 
      - db
    ports: 
      - "5000:3000"
  db:
    image: mongo:4.2.2
    restart: always
    volumes: 
      - "./mongodata:/data/db"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Fantastic88
    ports: 
      - "27019:27017"